[tool.poetry]
name = "main"
version = "0.1.0"
description = ""
authors = ["Emmanuel Ani <emmanuelani234@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
ultralytics = "^8.3.52"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
