name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ] # Trigger on pushes to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build and Push
      uses: docker/build-push-action@v3
      with:
        push: true # Push to Docker Hub
        context: .  # Build context
        file: ./Dockerfile # Path to Dockerfile
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/bloomzon:latest  # Replace with your Docker Hub username and image name
